/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccessFieldsMap
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class AccessFieldsMap   {
  @SerializedName("USERNAME")
  private String USERNAME = null;

  @SerializedName("CUSTOMERNUMBER")
  private String CUSTOMERNUMBER = null;

  @SerializedName("PIN")
  private String PIN = null;

  public AccessFieldsMap USERNAME(String USERNAME) {
    this.USERNAME = USERNAME;
    return this;
  }

   /**
   * Should be filled with the username if the Provider object signals this as mandatory.
   * @return USERNAME
  **/
  @ApiModelProperty(example = "null", value = "Should be filled with the username if the Provider object signals this as mandatory.")
  public String getUSERNAME() {
    return USERNAME;
  }

  public void setUSERNAME(String USERNAME) {
    this.USERNAME = USERNAME;
  }

  public AccessFieldsMap CUSTOMERNUMBER(String CUSTOMERNUMBER) {
    this.CUSTOMERNUMBER = CUSTOMERNUMBER;
    return this;
  }

   /**
   * Should be filled with the customer number if the Provider object signals this as mandatory.
   * @return CUSTOMERNUMBER
  **/
  @ApiModelProperty(example = "null", value = "Should be filled with the customer number if the Provider object signals this as mandatory.")
  public String getCUSTOMERNUMBER() {
    return CUSTOMERNUMBER;
  }

  public void setCUSTOMERNUMBER(String CUSTOMERNUMBER) {
    this.CUSTOMERNUMBER = CUSTOMERNUMBER;
  }

  public AccessFieldsMap PIN(String PIN) {
    this.PIN = PIN;
    return this;
  }

   /**
   * Should be filled with the PIN if the Provider object signals this as mandatory.
   * @return PIN
  **/
  @ApiModelProperty(example = "null", value = "Should be filled with the PIN if the Provider object signals this as mandatory.")
  public String getPIN() {
    return PIN;
  }

  public void setPIN(String PIN) {
    this.PIN = PIN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessFieldsMap accessFieldsMap = (AccessFieldsMap) o;
    return Objects.equals(this.USERNAME, accessFieldsMap.USERNAME) &&
        Objects.equals(this.CUSTOMERNUMBER, accessFieldsMap.CUSTOMERNUMBER) &&
        Objects.equals(this.PIN, accessFieldsMap.PIN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(USERNAME, CUSTOMERNUMBER, PIN);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessFieldsMap {\n");
    
    sb.append("    USERNAME: ").append(toIndentedString(USERNAME)).append("\n");
    sb.append("    CUSTOMERNUMBER: ").append(toIndentedString(CUSTOMERNUMBER)).append("\n");
    sb.append("    PIN: ").append(toIndentedString(PIN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

