/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InputFieldDescription;
import java.util.ArrayList;
import java.util.List;


/**
 * AccessDescription
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class AccessDescription   {
  @SerializedName("infoText")
  private String infoText = null;

  @SerializedName("fieldDescriptions")
  private List<InputFieldDescription> fieldDescriptions = new ArrayList<InputFieldDescription>();

  public AccessDescription infoText(String infoText) {
    this.infoText = infoText;
    return this;
  }

   /**
   * Information text by the provider as a description for required user actions during the account setup (e.g.,   \"Provided your financial institution has not given you a separate username, please enter  your account number as your username. Depending on your financial institution,  additional information such as a customer number can be entered. Most of the time  entering this information is optional.\")
   * @return infoText
  **/
  @ApiModelProperty(example = "null", value = "Information text by the provider as a description for required user actions during the account setup (e.g.,   \"Provided your financial institution has not given you a separate username, please enter  your account number as your username. Depending on your financial institution,  additional information such as a customer number can be entered. Most of the time  entering this information is optional.\")")
  public String getInfoText() {
    return infoText;
  }

  public void setInfoText(String infoText) {
    this.infoText = infoText;
  }

  public AccessDescription fieldDescriptions(List<InputFieldDescription> fieldDescriptions) {
    this.fieldDescriptions = fieldDescriptions;
    return this;
  }

  public AccessDescription addFieldDescriptionsItem(InputFieldDescription fieldDescriptionsItem) {
    this.fieldDescriptions.add(fieldDescriptionsItem);
    return this;
  }

   /**
   * Information to describe and facilitate validation of an access.
   * @return fieldDescriptions
  **/
  @ApiModelProperty(example = "null", value = "Information to describe and facilitate validation of an access.")
  public List<InputFieldDescription> getFieldDescriptions() {
    return fieldDescriptions;
  }

  public void setFieldDescriptions(List<InputFieldDescription> fieldDescriptions) {
    this.fieldDescriptions = fieldDescriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessDescription accessDescription = (AccessDescription) o;
    return Objects.equals(this.infoText, accessDescription.infoText) &&
        Objects.equals(this.fieldDescriptions, accessDescription.fieldDescriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(infoText, fieldDescriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessDescription {\n");
    
    sb.append("    infoText: ").append(toIndentedString(infoText)).append("\n");
    sb.append("    fieldDescriptions: ").append(toIndentedString(fieldDescriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

