/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AccessDescription;
import io.swagger.client.model.Provider;


/**
 * BankProvider
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class BankProvider extends Provider  {
  @SerializedName("bankCode")
  private String bankCode = null;

  @SerializedName("bic")
  private String bic = null;

  public BankProvider bankCode(String bankCode) {
    this.bankCode = bankCode;
    return this;
  }

   /**
   * Bank code number (BLZ, national, 8 digits)
   * @return bankCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "Bank code number (BLZ, national, 8 digits)")
  public String getBankCode() {
    return bankCode;
  }

  public void setBankCode(String bankCode) {
    this.bankCode = bankCode;
  }

  public BankProvider bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * Business Identifier Code (defined in ISO-9362)
   * @return bic
  **/
  @ApiModelProperty(example = "null", required = true, value = "Business Identifier Code (defined in ISO-9362)")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankProvider bankProvider = (BankProvider) o;
    return Objects.equals(this.bankCode, bankProvider.bankCode) &&
        Objects.equals(this.bic, bankProvider.bic) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankCode, bic, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankProvider {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    bankCode: ").append(toIndentedString(bankCode)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

