/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Notification;
import java.util.ArrayList;
import java.util.List;


/**
 * DailySummaryNotification
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class DailySummaryNotification extends Notification  {
  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("timeOfDay")
  private String timeOfDay = null;

  /**
   * Gets or Sets daysOfWeek
   */
  public enum DaysOfWeekEnum {
    @SerializedName("MONDAY")
    MONDAY("MONDAY"),
    
    @SerializedName("TUESDAY")
    TUESDAY("TUESDAY"),
    
    @SerializedName("WEDNESDAY")
    WEDNESDAY("WEDNESDAY"),
    
    @SerializedName("THURSDAY")
    THURSDAY("THURSDAY"),
    
    @SerializedName("FRIDAY")
    FRIDAY("FRIDAY"),
    
    @SerializedName("SATURDAY")
    SATURDAY("SATURDAY"),
    
    @SerializedName("SUNDAY")
    SUNDAY("SUNDAY");

    private String value;

    DaysOfWeekEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("daysOfWeek")
  private List<DaysOfWeekEnum> daysOfWeek = new ArrayList<DaysOfWeekEnum>();

  public DailySummaryNotification accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Identifier of the account to which this notification belongs
   * @return accountId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Identifier of the account to which this notification belongs")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public DailySummaryNotification timeOfDay(String timeOfDay) {
    this.timeOfDay = timeOfDay;
    return this;
  }

   /**
   * Time of the day when this notification should be triggered. Must be in the desired timezone or normalized to UTC. (ISO-8601; e.g.,  \"13:45.30.123456789+02:00\")
   * @return timeOfDay
  **/
  @ApiModelProperty(example = "null", required = true, value = "Time of the day when this notification should be triggered. Must be in the desired timezone or normalized to UTC. (ISO-8601; e.g.,  \"13:45.30.123456789+02:00\")")
  public String getTimeOfDay() {
    return timeOfDay;
  }

  public void setTimeOfDay(String timeOfDay) {
    this.timeOfDay = timeOfDay;
  }

  public DailySummaryNotification daysOfWeek(List<DaysOfWeekEnum> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
    return this;
  }

  public DailySummaryNotification addDaysOfWeekItem(DaysOfWeekEnum daysOfWeekItem) {
    this.daysOfWeek.add(daysOfWeekItem);
    return this;
  }

   /**
   * The days of the week on which these notification should be triggered. All entries must be unique.  Can be `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY` or `SUNDAY`
   * @return daysOfWeek
  **/
  @ApiModelProperty(example = "null", required = true, value = "The days of the week on which these notification should be triggered. All entries must be unique.  Can be `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY` or `SUNDAY`")
  public List<DaysOfWeekEnum> getDaysOfWeek() {
    return daysOfWeek;
  }

  public void setDaysOfWeek(List<DaysOfWeekEnum> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DailySummaryNotification dailySummaryNotification = (DailySummaryNotification) o;
    return Objects.equals(this.accountId, dailySummaryNotification.accountId) &&
        Objects.equals(this.timeOfDay, dailySummaryNotification.timeOfDay) &&
        Objects.equals(this.daysOfWeek, dailySummaryNotification.daysOfWeek) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, timeOfDay, daysOfWeek, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DailySummaryNotification {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    timeOfDay: ").append(toIndentedString(timeOfDay)).append("\n");
    sb.append("    daysOfWeek: ").append(toIndentedString(daysOfWeek)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

