/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;


/**
 * MonthlySummary
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class MonthlySummary   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("month")
  private String month = null;

  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("income")
  private Amount income = null;

  @SerializedName("outgoings")
  private Amount outgoings = null;

  @SerializedName("balance")
  private Amount balance = null;

  public MonthlySummary id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Internal ID of this monthlySummary (generated value)
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "Internal ID of this monthlySummary (generated value)")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public MonthlySummary month(String month) {
    this.month = month;
    return this;
  }

   /**
   * The month to which this entry belongs (year-month in ISO-8601: \"yyyy-MM\")
   * @return month
  **/
  @ApiModelProperty(example = "null", required = true, value = "The month to which this entry belongs (year-month in ISO-8601: \"yyyy-MM\")")
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public MonthlySummary accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * ID of account to which this entry belongs
   * @return accountId
  **/
  @ApiModelProperty(example = "null", required = true, value = "ID of account to which this entry belongs")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public MonthlySummary income(Amount income) {
    this.income = income;
    return this;
  }

   /**
   * Sum of all incoming transactions for this month
   * @return income
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sum of all incoming transactions for this month")
  public Amount getIncome() {
    return income;
  }

  public void setIncome(Amount income) {
    this.income = income;
  }

  public MonthlySummary outgoings(Amount outgoings) {
    this.outgoings = outgoings;
    return this;
  }

   /**
   * Sum of all outgoing transactions for this month
   * @return outgoings
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sum of all outgoing transactions for this month")
  public Amount getOutgoings() {
    return outgoings;
  }

  public void setOutgoings(Amount outgoings) {
    this.outgoings = outgoings;
  }

  public MonthlySummary balance(Amount balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Balance at end of month
   * @return balance
  **/
  @ApiModelProperty(example = "null", required = true, value = "Balance at end of month")
  public Amount getBalance() {
    return balance;
  }

  public void setBalance(Amount balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonthlySummary monthlySummary = (MonthlySummary) o;
    return Objects.equals(this.id, monthlySummary.id) &&
        Objects.equals(this.month, monthlySummary.month) &&
        Objects.equals(this.accountId, monthlySummary.accountId) &&
        Objects.equals(this.income, monthlySummary.income) &&
        Objects.equals(this.outgoings, monthlySummary.outgoings) &&
        Objects.equals(this.balance, monthlySummary.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, month, accountId, income, outgoings, balance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonthlySummary {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    outgoings: ").append(toIndentedString(outgoings)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

