/**
 * AHOI API
 * AHOI (working title) is our managed and flexible banking API designed to offer easy access to your users bank accounts.  [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Imprint](https://symbioticon.de/legal-notices/)  [Privacy Disclaimer](https://symbioticon.de/data-protection-guidelines/)  &copy; 2016 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ResponseObjectMap;


/**
 * TransferChallengeResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:10:08.564Z")
public class TransferChallengeResponse   {
  @SerializedName("transferTaskId")
  private Long transferTaskId = null;

  @SerializedName("responseObjects")
  private ResponseObjectMap responseObjects = null;

  public TransferChallengeResponse transferTaskId(Long transferTaskId) {
    this.transferTaskId = transferTaskId;
    return this;
  }

   /**
   * TransferTaskID &mdash; The referenced task for that payment challenge
   * @return transferTaskId
  **/
  @ApiModelProperty(example = "null", value = "TransferTaskID &mdash; The referenced task for that payment challenge")
  public Long getTransferTaskId() {
    return transferTaskId;
  }

  public void setTransferTaskId(Long transferTaskId) {
    this.transferTaskId = transferTaskId;
  }

  public TransferChallengeResponse responseObjects(ResponseObjectMap responseObjects) {
    this.responseObjects = responseObjects;
    return this;
  }

   /**
   * FieldSet &mdash; The required InputFields for that challenge
   * @return responseObjects
  **/
  @ApiModelProperty(example = "null", required = true, value = "FieldSet &mdash; The required InputFields for that challenge")
  public ResponseObjectMap getResponseObjects() {
    return responseObjects;
  }

  public void setResponseObjects(ResponseObjectMap responseObjects) {
    this.responseObjects = responseObjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferChallengeResponse transferChallengeResponse = (TransferChallengeResponse) o;
    return Objects.equals(this.transferTaskId, transferChallengeResponse.transferTaskId) &&
        Objects.equals(this.responseObjects, transferChallengeResponse.responseObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferTaskId, responseObjects);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferChallengeResponse {\n");
    
    sb.append("    transferTaskId: ").append(toIndentedString(transferTaskId)).append("\n");
    sb.append("    responseObjects: ").append(toIndentedString(responseObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

